### ISSUE TITLE
How to deselect all?

### ISSUE THREAD

**Issue by vimv** [mneofit/multiselect#1]
Hi, 

I would like to deselect all checkboxes by default programatically.

Since I don't see a `deselectAll()` method, I'm assuming that selectAll toggles the checkboxes.

This is what I'm doing but it doesn't work:
`$(selector).multiselect.selectAll();`

Is it possible that you can add to the README more info on how to deselect all via code?

Thank you.

**Comment by miket-dev** [comment]
Check the latest modifications, improved README.md for how to work with multiselect
Added `deselect` and `deselectAll` methods.
