### ISSUE TITLE
Does not refresh when original select box gets new attributes

### ISSUE THREAD

**Issue by harrington101** [mneofit/multiselect#3]
I have a multi-select box where the options available change as the page changes. Is it possible to update the options in this multi-select as the options in the original change?

**Comment by miket-dev** [comment]
Quite an old issue (and I am really sorry for that), but eventually I managed to work on it.
Use `destroy` method to destroy and recreate multiselect again. Refer to readme and demo for details. That's quite cheaper than adding a watcher for option set changes.
