### ISSUE TITLE
Chrome Autocomplete Blocks Drop Down

### ISSUE THREAD

**Issue by bradjoss** [mneofit/multiselect#4]
The default input box in Chrome (and possibly other browsers) appears after it has data from a previous submission.  This autocomplete blocks the top few selections in the check box list.

To fix:

in multiselect.core.js, add autocomplete off attribute.

//creates input field
	_createInputField: function () {
		var input = m_helper.textField({
			id : this._getInputFieldIdentifier(),
			class: 'multiselect-input',
			attributes: {
			    autocomplete: 'off'
			}
		}),

**Comment by miket-dev** [comment]
Added autocomplete="off" attribute, thank you
