### ISSUE TITLE
Enhancement request: Set Width

### ISSUE THREAD

**Issue by bradjoss** [mneofit/multiselect#5]
I am not a CSS guru, so maybe there was an easier way to solve this, but I had a hard time defining the width of the control when there were multiple instances on the page.  I ended up using this function to solve the problem, but I feel like is is still only half solved since it lacks grace.

function narrowSelect(colId, reduction) {
            var el1 = $(colId + "_multiSelect");
            el1.css("width", el1.width() - reduction);

            var el2 = $(colId + "_input");
            el2.css("width", el2.width() - reduction);
        }

If you could provide an easier way to specific width for the outer control (and that methodology took care of all the inner control widths), it would be a nice to have.

Again, thanks!

**Comment by miket-dev** [comment]
Quite an old issue (and I am really sorry for that), but eventually I managed to work on it.
Fixed the css to set the width for multiselect as you want, refer to demo for sample.
Shortly, you should set the style for the select as following:
```
#(initial_select_id_or_name)_multiSelect {
  width: 450px;
}
```
