### ISSUE TITLE
Initial "selected" options

### ISSUE THREAD

**Issue by markteunen65** [mneofit/multiselect#6]
The initial selected options are not checked (class=active) in the itemlist

    <select id='testSelect1' multiple>
        <option value='1'>Item 1</option>
        <option value='2' selected>Item 2</option>
        <option value='3'>Item 3</option>
        <option value='4' selected>Item 4</option>
        <option value='5'>Item 5</option>
    </select>

**Comment by jjacksondotnet** [comment]
same here.
Having trouble pre-selecting values.

**Comment by miket-dev** [comment]
@markteunen65 @jjacksondotnet fixed, feel free to recreate the issue if it happens again
