### ISSUE TITLE
Disable and enable 

### ISSUE THREAD

**Issue by ambatidilip** [mneofit/multiselect#7]
How can i disable and enable the control using multiselect. i have tried $('#id').prop('disabled', true) but not working

**Comment by miket-dev** [comment]
Added `setIsEnabled` method, which accepts boolean value, indicating whether this control is enabled or not. Refer to demo and readme for details.

**Comment by Farufon** [comment]
I am getting this error in my rails .erb page.  

If I change the extension to .html, then it works. 

     Uncaught TypeError: document.multiselect is not a function

What am I doing wrong?
